# Import necessary libraries
import asyncio  # For handling asynchronous operations
import os  # For environment variable access
import sys  # For system-specific parameters and functions
import json  # For handling JSON data (used when printing function declarations)

# Import MCP client components
from typing import Optional  # For type hinting optional values
from contextlib import AsyncExitStack  # For managing multiple async tasks
from mcp import ClientSession, StdioServerParameters  # MCP session management
from mcp.client.stdio import stdio_client  # MCP client for standard I/O communication

# Import Google's Gen AI SDK
from google import genai
from google.genai import types
from google.genai.types import Tool, FunctionDeclaration
from google.genai.types import GenerateContentConfig

from dotenv import load_dotenv  # For loading API keys from a .env file

# Load environment variables from .env file
load_dotenv()


class MCPClient:
    def __init__(self):
        """Initialize the MCP client and configure the Gemini API."""
        self.session: Optional[ClientSession] = None  # MCP session for communication
        self.exit_stack = AsyncExitStack()  # Manages async resource cleanup

        # Conversation history (list of types.Content) so multi-turn chats
        # have context. Populated by process_query, trimmed to the last
        # MAX_HISTORY_TURNS entries to bound token usage.
        self.history: list = []
        self.MAX_HISTORY_TURNS = 20

        # Retrieve the Gemini API key from environment variables
        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if not gemini_api_key:
            raise ValueError(
                "GEMINI_API_KEY not found. Please add it to your .env file."
            )

        # Configure the Gemini AI client
        self.genai_client = genai.Client(api_key=gemini_api_key)

    async def connect_to_server(self, server_script_path: str):
        """Connect to the MCP server and list available tools."""

        if server_script_path.endswith(".py"):
            # Prefer the server's own venv Python so it gets its own installed
            # packages (e.g. google-auth-oauthlib, google-api-python-client).
            # Falls back to this process's interpreter if no venv is found.
            server_dir = os.path.dirname(os.path.abspath(server_script_path))
            venv_python = os.path.join(server_dir, ".venv", "bin", "python")
            command = venv_python if os.path.exists(venv_python) else sys.executable
        else:
            command = "node"

        # Define the parameters for connecting to the MCP server.
        # Pass --server_type stdio so the server communicates over stdin/stdout
        # rather than starting an SSE/HTTP server.
        server_params = StdioServerParameters(
            command=command, args=[server_script_path, "--server_type", "stdio"]
        )

        # Establish communication with the MCP server using standard input/output (stdio)
        stdio_transport = await self.exit_stack.enter_async_context(
            stdio_client(server_params)
        )

        # Extract the read/write streams from the transport object
        self.stdio, self.write = stdio_transport

        # Initialize the MCP client session, which allows interaction with the server
        self.session = await self.exit_stack.enter_async_context(
            ClientSession(self.stdio, self.write)
        )

        # Send an initialization request to the MCP server
        await self.session.initialize()

        # Request the list of available tools from the MCP server
        response = await self.session.list_tools()
        tools = response.tools  # Extract the tool list from the response

        # Print a message showing the names of the tools available on the server
        print("\nConnected to server with tools:", [tool.name for tool in tools])

        # Convert MCP tools to Gemini format
        self.function_declarations = convert_mcp_tools_to_gemini(tools)

    async def process_query(self, query: str) -> str:
        """
        Process a user query using the Gemini API and execute tool calls if needed.

        Args:
            query (str): The user's input query.

        Returns:
            str: The response generated by the Gemini model.
        """

        # Format user input as a structured Content object for Gemini
        user_prompt_content = types.Content(
            role="user",  # Indicates that this is a user message
            parts=[
                types.Part.from_text(text=query)
            ],  # Convert the text query into a Gemini-compatible format
        )

        # Append the new user turn to persistent history so multi-turn chats
        # have context. We send the full history with each request.
        self.history.append(user_prompt_content)

        # Send conversation history to Gemini with available tools
        response = self.genai_client.models.generate_content(
            model="gemini-2.0-flash-lite",  # Specifies which Gemini model to use
            contents=self.history,
            config=types.GenerateContentConfig(
                tools=self.function_declarations,  # Pass the list of available MCP tools for Gemini to use
            ),
        )

        # Initialize variables to store final response text and assistant messages
        final_text = []  # Stores the final formatted response

        # Process the response received from Gemini
        for candidate in response.candidates:
            if candidate.content.parts:  # Ensure response has content
                for part in candidate.content.parts:
                    if isinstance(
                        part, types.Part
                    ):  # Check if part is a valid Gemini response unit
                        if (
                            part.function_call
                        ):  # If Gemini suggests a function call, process it
                            # Extract function call details
                            function_call_part = (
                                part  # Store the function call response
                            )
                            tool_name = (
                                function_call_part.function_call.name
                            )  # Name of the MCP tool Gemini wants to call
                            tool_args = (
                                function_call_part.function_call.args
                            )  # Arguments required for the tool execution

                            # Print debug info: Which tool is being called and with what arguments
                            print(
                                f"\n[Gemini requested tool call: {tool_name} with args {tool_args}]"
                            )

                            # Execute the tool using the MCP server
                            try:
                                result = await self.session.call_tool(
                                    tool_name, tool_args
                                )  # Call MCP tool with arguments
                                # result.content is a list of TextContent /
                                # ImageContent objects. Extract plain text so
                                # the response is JSON-serializable for Gemini.
                                tool_output = "\n".join(
                                    getattr(c, "text", str(c))
                                    for c in (result.content or [])
                                )
                                function_response = {"result": tool_output}
                            except Exception as e:
                                function_response = {
                                    "error": str(e)
                                }  # Handle errors if tool execution fails

                            # Format the tool response for Gemini in a way it understands
                            function_response_part = types.Part.from_function_response(
                                name=tool_name,  # Name of the function/tool executed
                                response=function_response,  # The result of the function execution
                            )

                            # Structure the tool response as a Content object for Gemini
                            function_response_content = types.Content(
                                role="tool",  # Specifies that this response comes from a tool
                                parts=[
                                    function_response_part
                                ],  # Attach the formatted response part
                            )

                            # Wrap the function-call Part in a Content object —
                            # generate_content's `contents` list expects Content,
                            # not raw Part objects.
                            function_call_content = types.Content(
                                role="model",
                                parts=[function_call_part],
                            )

                            # Append the function-call and tool-response turns to
                            # history so future queries can see them, then send
                            # the full history back to Gemini.
                            self.history.append(function_call_content)
                            self.history.append(function_response_content)

                            response = self.genai_client.models.generate_content(
                                model="gemini-2.0-flash-lite",  # Use the same model
                                contents=self.history,
                                config=types.GenerateContentConfig(
                                    tools=self.function_declarations,  # Provide the available tools for continued use
                                ),
                            )

                            # Extract final response text from Gemini after processing the tool call
                            follow_up = response.candidates[0].content
                            for follow_part in follow_up.parts or []:
                                if getattr(follow_part, "text", None):
                                    final_text.append(follow_part.text)
                            self.history.append(follow_up)
                        else:
                            # If no function call was requested, simply add Gemini's text response
                            final_text.append(part.text)
                # Persist the model turn (text-only path) to history
                if not any(
                    getattr(p, "function_call", None)
                    for p in (candidate.content.parts or [])
                ):
                    self.history.append(candidate.content)

        # Bound history to the last MAX_HISTORY_TURNS Content entries so token
        # usage stays predictable across long sessions.
        if len(self.history) > self.MAX_HISTORY_TURNS:
            self.history = self.history[-self.MAX_HISTORY_TURNS :]

        # Return the combined response as a single formatted string
        return "\n".join(final_text)

    async def chat_loop(self):
        """Run an interactive chat session with the user."""
        print("\nMCP Client Started! Type 'quit' to exit.")

        while True:
            query = input("\nQuery: ").strip()
            if query.lower() == "quit":
                break

            # Process the user's query and display the response
            response = await self.process_query(query)
            print("\n" + response)

    async def cleanup(self):
        """Clean up resources before exiting."""
        await self.exit_stack.aclose()


def clean_schema(schema):
    """
    Recursively returns a copy of the JSON schema with 'title' fields removed.

    Pure function — does not mutate the input — so the original MCP tool
    schemas remain intact for any other consumer.
    """
    if not isinstance(schema, dict):
        return schema

    cleaned = {k: v for k, v in schema.items() if k != "title"}
    if isinstance(cleaned.get("properties"), dict):
        cleaned["properties"] = {
            k: clean_schema(v) for k, v in cleaned["properties"].items()
        }
    return cleaned


def convert_mcp_tools_to_gemini(mcp_tools):
    """
    Converts MCP tool definitions to the correct format for Gemini API function calling.

    Returns a single-element list containing one Tool that wraps every
    FunctionDeclaration. Gemini expects all declarations grouped under one
    Tool — passing one Tool per function is non-standard and can cause
    unexpected behavior.

    Args:
        mcp_tools (list): List of MCP tool objects with 'name', 'description', and 'inputSchema'.

    Returns:
        list: [Tool(function_declarations=[...])]
    """
    function_declarations = [
        FunctionDeclaration(
            name=tool.name,
            description=tool.description,
            parameters=clean_schema(tool.inputSchema),
        )
        for tool in mcp_tools
    ]

    return [Tool(function_declarations=function_declarations)]


async def main():
    """Main function to start the MCP client."""
    if len(sys.argv) < 2:
        print("Usage: python client.py <path_to_server_script>")
        sys.exit(1)

    client = MCPClient()
    try:
        # Connect to the MCP server and start the chat loop
        await client.connect_to_server(sys.argv[1])
        await client.chat_loop()
    finally:
        # Ensure resources are cleaned up
        await client.cleanup()


if __name__ == "__main__":
    # Run the main function within the asyncio event loop
    asyncio.run(main())
